config/routes.rb
Rails.application.routes.draw do

  resources :players, except: [:show]
  resources :games do
    resources :attendances, except: [:index, :show]
  end
  resources :games_past, only: [:index]
  get 'calendar', action: :calendar, controller: 'games'
  root 'staticpages#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendance.rb
class Attendance < ApplicationRecord
  belongs_to :game
  belongs_to :player
  validates :game_id, uniqueness: { scope: :player_id }
end

app/models/game.rb
class Game < ApplicationRecord
  has_many :attendances, dependent: :destroy
  has_many :players, through: :attendances

  def start_time
    self.date
  end
end

app/models/player.rb
class Player < ApplicationRecord
  has_many :attendances, dependent: :destroy
  has_many :games, through: :attendances
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/attendances_controller.rb
class AttendancesController < ApplicationController
  def new
    @game = Game.find(params[:game_id])
    @attendance = @game.attendances.build
    @player = Player.find_by(id: params[:player_id])
  end

  def create
    game = Game.find(params[:game_id])
    @attendance = game.attendances.new(attendance_params)
    name = Player.find(params[:attendance][:player_id]).name
    if @attendance.save
      flash[:success] = "#{name}さんの出欠情報を登録しました"
      redirect_to game_path(game)
    else
      redirect_to root_url
    end
  end

  def edit
    @game = Game.find(params[:game_id])
    @player = Player.find_by(id: params[:player_id])
    @attendance = @player.attendances.find_by(game_id: @game.id)
  end

  def update
    @attendance = Attendance.find(params[:id])
    if @attendance.update(attendance_params)
      name = Player.find(params[:attendance][:player_id]).name
      flash[:success] = "#{name}さんの出欠情報を編集しました"
      redirect_to game_path(params[:game_id])
    else
      flash[:danger] = "出欠の編集に失敗しました"
      redirect_to game_path(params[:game_id])
    end
  end

  private
    def attendance_params
      params.require(:attendance).permit(:attendance, :judge, :comment, :player_id)
    end

end

app/controllers/games_controller.rb
class GamesController < ApplicationController

  def index
    @games = Game.where('date >= ?', Date.today - 1).order(date: :asc)
  end

  def calendar
    @games = Game.where('date >= ?', Date.today - 1).order(date: :asc)
  end

  def new
    @game = Game.new
  end

  def create
    game = Game.new(game_params)
    if game.save
      flash[:success] = "#{game.title}を登録しました"
      redirect_to games_path
    else
      flash[:danger] = game.errors.full_messages
      redirect_to new_game_path(game)
    end
  end

  def edit
    @game = Game.find_by(id: params[:id])
  end

  def update
    game = Game.find_by(id: params[:id])
    if game.update(game_params)
      flash[:success] = "#{game.title}を編集しました"
      redirect_to games_path
    else
      flash[:danger] = game.errors.full_messages
      redirect_to edit_game_path(game)
    end
  end

  def show
    @game = Game.find_by(id: params[:id])
    @players = Player.all.order(:back_number)
    @attendances = @game.attendances
  end

  def destroy
    game = Game.find_by(id: params[:id])
    if game.destroy
      flash[:success] = "#{game.title}を削除しました"
      redirect_to games_path
    else
      flash[:danger] = game.errors.full_messages
      redirect_to games_path
    end
  end

  private
    def game_params
      params.require(:game).permit(:title, :date, :place, :time, :meetingtime)
    end
end

app/controllers/games_past_controller.rb
class GamesPastController < ApplicationController
  def index
    @games = Game.where('date < ?', Date.today - 1).order(date: :desc)
  end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  def index
    @players = Player.all.order(:back_number)
  end

  def new
    @player = Player.new
  end

  def create
    @player = Player.new(player_params)
    if @player.save
      flash[:success] = "#{@player.name}さん(背番号:#{@player.back_number})を登録しました"
      redirect_to players_path
    else
      flash.now[:danger] = @player.errors.full_messages
      render 'new'
    end
  end

  def edit
    @player = Player.find_by(id: params[:id])
  end

  def update
    player = Player.find(params[:id])
    if player.update(player_params)
      flash[:success] = "#{player.name}さん(背番号:#{player.back_number})に編集しました"
      redirect_to players_path
    else
      flash[:danger] = player.errors.full_messages
      redirect_to edit_player_path(player)
    end
  end

  def destroy
    player = Player.find(params[:id])
    if player.destroy
      flash[:success] = "#{player.name}さん(背番号:#{player.back_number})を削除しました"
      redirect_to players_path
    else
      flash[:danger] = player.errors.full_messages
      redirect_to players_path
    end
  end

  private
    def player_params
      params.require(:player).permit(:back_number, :name)
    end
end

app/controllers/staticpages_controller.rb
class StaticpagesController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attendances_helper.rb
module AttendancesHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/games_past_helper.rb
module GamesPastHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/helpers/staticpages_helper.rb
module StaticpagesHelper
end

app/views/attendances/_form.html.erb
<p><%= @player.name %></p>
<%= form_for [@game, @attendance] do |a| %>
  <%= a.hidden_field :player_id, value: @player.id %>
  <div class="form-group">
    <%= a.label :attendance, "出欠" %>
    <%= a.select :attendance, [["出", "出"], ["欠", "欠"], ["未", "未"]], include_blank: true, class:"form-control" %>
  </div>
  <div class="form-group">
    <%= a.label :judge, "審判" %>
    <%= a.select :judge, [["主", "主"], ["副", "副"], ["四", "四"]], include_blank: true, class:"form-control" %>
  </div>
  <div class="form-group">
    <%= a.label :comment, "コメント" %>
    <%= a.text_field :comment, class:"form-control" %>
  </div>
  <div class="form-group">
    <%= a.submit '確定'%>
  </div>
<% end %>

app/views/attendances/edit.html.erb
<div class="container">
  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="/">Home</a></li>
      <li class="breadcrumb-item"><%= link_to "試合一覧", games_path %></li>
      <li class="breadcrumb-item active" aria-current="page">出欠登録</li>
    </ol>
  </nav>
  <%= render 'games/gamedetail' %>
  <%= render 'form' %>
</div>

app/views/attendances/new.html.erb
<div class="container">
  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="/">Home</a></li>
      <li class="breadcrumb-item"><%= link_to "試合一覧", games_path %></li>
      <li class="breadcrumb-item active" aria-current="page">出欠登録</li>
    </ol>
  </nav>
  <%= render 'games/gamedetail' %>
  <%= render 'form' %>
</div>

app/views/games/_form.html.erb
<%= form_for @game do |g| %>
  <div class="form-row">
    <div class="form-group col-11">
      <%= g.label :date %>
      <%= g.date_select :date, use_month_numbers: true %>
    </div>
    <div class="form-group col-7">
      <%= g.text_field :title, placeholder: "対戦相手", class: "form-control" %>
    </div>
    <div class="form-group col-7">
      <%= g.text_field :place, placeholder: "対戦場所", class: "form-control" %>
    </div>
    <div class="form-group col-11">
      <%= g.label :meetingtime, "集合時刻" %>
      <%= g.time_select :meetingtime, include_blank: true, minute_step: 10 %>
    </div>
    <div class="form-group col-11">
      <%= g.label :time, "試合時刻" %>
      <%= g.time_select :time, include_blank: true, minute_step: 10 %>
    </div>
    <div class="form-group col-11">
      <%= g.submit '確定' %>
    </div>
  </div>
<% end %>

app/views/games/_gamedetail.html.erb
<p><%= "試合日　：#{@game.date.strftime('%Y年%m月%d日(%a)')}" %></br>
<%= "#{@game.title}" %></br>
<%= "対戦場所：#{@game.place}" %></br>
<%= "集合時刻：#{@game.meetingtime.strftime('%H:%M')}" %></br>
<%= "開始時刻：#{@game.time.strftime('%H:%M')}" %></p>
<hr>

app/views/games/calendar.html.erb
<div class="container">
  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="/">Home</a></li>
      <li class="breadcrumb-item active" aria-current="page">試合一覧</li>
    </ol>
  </nav>
  <%= month_calendar events: @games do |date, games| %>
    <%= date.strftime("%-d") %>

    <% games.each do |game| %>
      <div>
        <%= link_to "☆", game_path(game)  %>
      </div>
    <% end %>
  <% end %>
    <ul class="list-group list-group-flush">
      <% @games.each do |game| %>
      <li class="list-group-item">
        <p>
          <%= link_to "#{game.title}", game_path(game) %></br>
          <%= "試合日：#{game.date}　　場所：#{game.place}" %></br>
          <%= "☆参加人数：#{game.attendances.where(attendance: "出").count}人" %>
        </p>
        <%= link_to "出欠", game_path(game), class: "btn btn-outline-primary btn-sm float-left" %>
        <%= link_to "試合情報編集", edit_game_path(game), class: "btn btn-outline-secondary btn-sm float-right" %>
      </li>
      <% end %>
    </ul>
</div>

app/views/games/edit.html.erb
<div class="container">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="/">Home</a></li>
    <li class="breadcrumb-item"><a href=<%= games_path %>>試合一覧</a></li>
    <li class="breadcrumb-item active" aria-current="page">試合情報編集</li>
  </ol>
  <h3>試合情報修正</h3>
  <%= render 'form' %>
  <%= link_to "削除", game_path(@game), method: :delete, data: {confirm: '本当に削除していいですか？' }, class: "btn btn-outline-danger btn-sm float-left" %>
</div>

app/views/games/index.html.erb
<div class="container">
  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="/">Home</a></li>
      <li class="breadcrumb-item active" aria-current="page">試合一覧</li>
    </ol>
  </nav>
  <h3>試合一覧</h3>
    <ul class="list-group list-group-flush">
      <% @games.each do |game| %>
      <li class="list-group-item">
        <p>
          <%= link_to "#{game.title}", game_path(game) %></br>
          <%= "試合日：#{game.date}　　場所：#{game.place}" %></br>
          <%= "☆参加人数：#{game.attendances.where(attendance: "出").count}人" %>
        </p>
        <%= link_to "出欠", game_path(game), class: "btn btn-outline-primary btn-sm float-left" %>
        <%= link_to "試合情報編集", edit_game_path(game), class: "btn btn-outline-secondary btn-sm float-right" %>
      </li>
      <% end %>
    </ul>
</div>

app/views/games/new.html.erb
<div class="container">
  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="/">Home</a></li>
      <li class="breadcrumb-item active" aria-current="page">試合登録</li>
    </ol>
  </nav>
  <h3>試合情報登録</h3>
  <%= render 'form' %>
</div>

app/views/games/show.html.erb
<div class="container">
  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="/">Home</a></li>
      <li class="breadcrumb-item"><a href=<%= games_path %>>試合一覧</a></li>
      <li class="breadcrumb-item active" aria-current="page">出欠登録</li>
    </ol>
  </nav>
  <%= render 'gamedetail' %>
  <%= "☆参加人数：#{@game.attendances.where(attendance: "出").count}人" %>
    <ul class="list-group list-group-flush">
      <% @players.each do |p| %>
        <% attend = p.attendances.find_by(game_id: @game.id) %>
        <li class="list-group-item">
          <div class="row">
            <% if attend.blank? %>
              <div class="col-5">
                <%= link_to "#{p.back_number} #{p.name}", new_game_attendance_url(@game, player_id: p.id) %>
              </div>
            <% else %>
              <div class='col-5'>
                <%= link_to "#{p.back_number} #{p.name}", edit_game_attendance_url(@game, attend.id, player_id: p.id) %>
              </div>
              <div class="col-7">
                <%= attend.attendance unless attend.attendance.nil? %>
                <%= attend.judge unless attend.judge.nil? %>
              </div>
              <div class="col-7 offset-5">
                <%= attend.comment unless attend.comment.nil? %>
              </div>
            <% end %>
          </div>
        </li>
      <% end %>
    </ul>
</div>

app/views/games_past/index.html.erb
<div class="container">
  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="/">Home</a></li>
      <li class="breadcrumb-item active" aria-current="page">試合一覧</li>
    </ol>
  </nav>
  <h3>過去の試合一覧</h3>
    <ul class="list-group list-group-flush">
      <% @games.each do |game| %>
      <li class="list-group-item">
        <p>
          <%= link_to "#{game.title}", game_path(game) %></br>
          <%= "試合日：#{game.date}　　場所：#{game.place}" %></br>
          <%= "☆参加人数：#{game.attendances.where(attendance: "出").count}人" %>
        </p>
        <%= link_to "出欠", game_path(game), class: "btn btn-outline-primary btn-sm float-left" %>
        <%= link_to "試合情報編集", edit_game_path(game), class: "btn btn-outline-secondary btn-sm float-right" %>
      </li>
      <% end %>
    </ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AttendanceApp</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% flash.each do |message_type, message| %>
      <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/players/_form.html.erb
<%= form_for @player do |f| %>
   <div class="form-group col-3">
     <%= f.label :back_number, "背番号" %>
     <%= f.number_field :back_number, min: 0, class:"form-control" %>
   </div>
   <div class="form-group col-10">
     <%= f.label :name, "名前" %>
     <%= f.text_field :name, class:"form-control" %>
   </div>
   <div class="form-group">
     <%= f.submit '確定' %>
   </div>
<% end %>

app/views/players/edit.html.erb
<div class="container">
  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="/">Home</a></li>
      <li class="breadcrumb-item active" aria-current="page">選手編集</li>
    </ol>
    <h3>選手編集</h3>
    <%= render "form" %>
</div>

app/views/players/index.html.erb
<div class="container">
  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="/">Home</a></li>
      <li class="breadcrumb-item active" aria-current="page">選手一覧</li>
    </ol>
  </nav>
<h3>選手一覧</h3>
  <ul class="list-group list-group-flush">
    <% @players.each do |player| %>
      <li class="list-group-item">
        <%= "背番号:#{player.back_number}  #{player.name}" %>
        <%= link_to "削除", player_path(player), method: :delete, data: {confirm: '本当に削除していいですか？' }, class: "btn btn-outline-danger btn-sm float-right" %>
        <%= link_to "編集", edit_player_path(player), class: "btn btn-outline-primary btn-sm float-right" %>
      </li>
    <% end %>
  </ul>
</div>

app/views/players/new.html.erb
<div class="container">
  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="/">Home</a></li>
      <li class="breadcrumb-item active" aria-current="page">選手登録</li>
    </ol>
  </nav>
  <h3>新規選手登録</h3>
  <%= render "form" %>
</div>

app/views/staticpages/index.html.erb
<div class="container">
  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item active" aria-current="page">Home</li>
    </ol>
  </nav>
  <div class="text-center jumbotron">
    <h3 class=>NECサッカー部</h3>
    <%= link_to "出欠登録", games_path, class: "btn btn-primary btn-block" %>
  </div>
  <ul class="list-group list-group-flush">
    <li class="list-group-item">
      <%= link_to "カレンダー", calendar_path, class: "btn btn-outline-success btn-block" %>
    </li>
    <li class="list-group-item">
      <%= link_to "選手一覧", players_path, class: "btn btn-outline-danger btn-block" %>
    </li>
    <li class="list-group-item">
      <%= link_to "試合登録", new_game_path, class: "btn btn-outline-warning btn-block" %>
    </li>
    <li class="list-group-item">
      <%= link_to "選手登録", new_player_path, class: "btn btn-outline-info btn-block" %>
    </li>
    <li class="list-group-item">
      <%= link_to "過去の試合情報", games_past_index_path, class: "btn btn-outline-secondary btn-block" %>
    </li>
  </ul>
</div>